server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-hystrix-order
eureka:
  client:
    #把自己注册进eureka
    register-with-eureka: true
    # 指示此客户端是否应从 eureka * 服务器获取 eureka 注册表信息
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka

# 此次如果开启了服务降级先得对ribbon进行修改时间，至少要比服务降级的时间长
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
#    serverMethod:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000